### ISSUE TITLE
有HF或魔搭的在线体验版本吗？

### ISSUE THREAD

**Issue by MysteryMulberry** [IEIT-Yuan/yuanchat#14]

**Comment by Iamlovingit** [comment]
有exe版本发布，可从modelscope上下载模型体验。具体参考[LINK](https://github.com/IEIT-Yuan/YuanChat/blob/main/docs/%E6%8E%A8%E5%87%BAWindows%E6%A1%8C%E9%9D%A2%E7%89%88YuanChat.exe.md)

**Comment by Huifu1018** [comment]
> _No description provided._

魔搭在线体验：https://modelscope.cn/studios/YuanLLM/yuan/summary
