### ISSUE TITLE
请教下这个本地模型在本地电脑部署有合规的问题吗（公司的限制）？ 模型属于已经备案状态不？谢谢

### ISSUE THREAD

**Issue by likeliu1986** [IEIT-Yuan/yuanchat#15]

**Comment by Huifu1018** [comment]
> _No description provided._

源2.0模型已经提交备案申请，近期会完成算法备案；
YuanChat属于开源软件，不会对您的系统、信息等私域数据进行上传、篡改与侵入，只要遵循YuanChat[开源许可协议](https://github.com/IEIT-Yuan/YuanChat/blob/main/LICENSE-YuanChat)，即可进行部署与使用，不存在合规问题；
同样，使用源2.0模型也需要遵守相关[开源协议](https://github.com/IEIT-Yuan/Yuan-2.0/blob/main/LICENSE-Yuan)。
