### ISSUE TITLE
本地部署报错

### ISSUE THREAD

**Issue by Legionee** [IEIT-Yuan/yuanchat#7]
<img width="954" alt="微信图片_20240118083841" src="https://github.com/IEIT-Yuan/YuanChat/assets/151610959/b0d3471c-09e0-4f87-a98b-94b1c014aff1">
<img width="954" alt="微信图片_20240118083842" src="https://github.com/IEIT-Yuan/YuanChat/assets/151610959/de803e4d-2ecf-423e-abc4-89a701862889">
本地部署报错  可以帮看下是什么问题吗

**Comment by Huifu1018** [comment]
> <img alt="微信图片_20240118083841" width="954" src="https://private-user-images.githubusercontent.com/151610959/297561304-b0d3471c-09e0-4f87-a98b-94b1c014aff1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDkxMjgsIm5iZiI6MTcwNTU0ODgyOCwicGF0aCI6Ii8xNTE2MTA5NTkvMjk3NTYxMzA0LWIwZDM0NzFjLTA5ZTAtNGY4Ny1hOThiLTk0YjFjMDE0YWZmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwMzMzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjQ4NzQyYmFlYTk5YmJmMDlmZGUxNWRhYmFmNzU5MGFiODlmNjE1ZTkzOGU5M2RlOTc5ZTIyNWE0MjVhMjhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2x4-R_hPp1h-WtAgPc7SYm76_XBV5uSP9eteqLW-RZw"> <img alt="微信图片_20240118083842" width="954" src="https://private-user-images.githubusercontent.com/151610959/297561312-de803e4d-2ecf-423e-abc4-89a701862889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDkxMjgsIm5iZiI6MTcwNTU0ODgyOCwicGF0aCI6Ii8xNTE2MTA5NTkvMjk3NTYxMzEyLWRlODAzZTRkLTJlY2YtNDIzZS1hYmM0LTg5YTcwMTg2Mjg4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwMzMzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OGI2OGM1Y2UzOTJiNDQzYmJjMjkzNjJjMWViYjJiYmM5ODkxNGU1Yzk3MmIzNGM2YzkzYTdlNTE4NWMyZDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h40cOJw8PqFSMcPIUnnaWNLUfWMwB-H4vDlOEDqiZuw"> 本地部署报错 可以帮看下是什么问题吗

@Iamlovingit

**Comment by Iamlovingit** [comment]
@Legionee 你好，能发一下容器的启动命令吗？看现象应该是在加载的过程中出现的问题

**Comment by Legionee** [comment]
> @Legionee 你好，能发一下容器的启动命令吗？看现象应该是在加载的过程中出现的问题

docker run -d --name all-in-one -p 5050:5050 -v d:\yuandemo\Yuan2-2B-hf:/models yuanmodel/yuanchat:all-cpu

**Comment by Legionee** [comment]
![image](https://github.com/IEIT-Yuan/YuanChat/assets/151610959/a606644b-0afb-40e8-8201-a7e2c7d02d83)

**Comment by Iamlovingit** [comment]
进到容器内部，看下/models目录下有东西吗？
```shell
1. docker exec -it all-in-one bash
2. ls /models
```

**Comment by Legionee** [comment]
> 进到容器内部，看下/models目录下有东西吗？
> 
> ```shell
> 1. docker exec -it all-in-one bash
> 2. ls /models
> ```

没有东西   空空如也

**Comment by Iamlovingit** [comment]
OK，那问题定位了。先确认下是否已经下载了模型，没有下载的话，可以参照这个说明去下载[link](https://github.com/IEIT-Yuan/YuanChat/blob/main/docs/%E5%9C%A8%E7%AC%94%E8%AE%B0%E6%9C%AC%E4%B8%8A%E5%BF%AB%E9%80%9F%E9%83%A8%E7%BD%B2YuanModel%E5%92%8CYuanChat.md#22-%E4%B8%8B%E8%BD%BD%E6%A8%A1%E5%9E%8B)

**Comment by Legionee** [comment]
![image](https://github.com/IEIT-Yuan/YuanChat/assets/151610959/a29c7bb8-26ba-4f88-9607-7854c5f7f69e)
又去重新下载了一遍，重新走了遍流程，models下面还是没有东西

**Comment by Iamlovingit** [comment]
@Legionee 方便提供一下模型的存放的路径吗？`Demo`里面的路径是`D:\yuandemo`

**Comment by Legionee** [comment]
![image](https://github.com/IEIT-Yuan/YuanChat/assets/151610959/1a4011ba-5257-4a2c-a106-4765bd88d742)

D:\yuandemo\Yuan2-2B-hf

**Comment by Iamlovingit** [comment]
![1](https://github.com/IEIT-Yuan/YuanChat/assets/38182824/2ba6d09e-4bc4-4733-8699-f891465905b3)
看一下这里，再发个截图
再看下`files`标签下面，`/models`路径的内容

**Comment by Legionee** [comment]
![image](https://github.com/IEIT-Yuan/YuanChat/assets/151610959/7bcc1ba3-48f2-477c-99ed-23dee9bfa628)

**Comment by Iamlovingit** [comment]
再看下`files`标签下面，`/models`路径的内容

**Comment by Legionee** [comment]
![Uploading image.png…]()
这个下面是空的

**Comment by Legionee** [comment]
![image](https://github.com/IEIT-Yuan/YuanChat/assets/151610959/c3f3d7fc-f8aa-477f-b8c2-6ada8b56b96e)
这个下面是空的

**Comment by Iamlovingit** [comment]
试一下这个启动命令
```shell
docker run -d --name all-in-one -p 5050:5050 -v /d/yuandemo/Yuan2-2B-hf:/models yuanmodel/yuanchat:all-cpu
```

**Comment by Legionee** [comment]
依旧不行  models下面还是没有东西

**Comment by Iamlovingit** [comment]
有些奇怪，能提供一下你的系统版本和docker版本吗

**Comment by Iamlovingit** [comment]
![image](https://github.com/IEIT-Yuan/YuanChat/assets/38182824/2ccc456e-89c6-422a-9d54-43b12c9de67e)
发现你的盘符不是`D:\`, 那你试下这个命令
```shell
docker run -d --name all-in-one -p 5050:5050 -v Data:\yuandemo\Yuan2-2B-hf:/models yuanmodel/yuanchat:all-cpu
```

**Comment by Iamlovingit** [comment]
通过`powershell`进入到`Yuan2-2B-hf`目录，然后执行`pwd`命令，把结果贴出来

**Comment by Legionee** [comment]
![image](https://github.com/IEIT-Yuan/YuanChat/assets/151610959/f1451961-7836-473b-b1cc-60d5efd0a8a7)
docker engine v24.0.7

**Comment by Legionee** [comment]
![image](https://github.com/IEIT-Yuan/YuanChat/assets/151610959/b9c09f0f-2c7e-4bdd-b8d4-a027d16f6d52)

**Comment by Iamlovingit** [comment]
通过powershell进入到Yuan2-2B-hf目录，然后执行ls命令，再把结果贴出来

**Comment by Legionee** [comment]
![image](https://github.com/IEIT-Yuan/YuanChat/assets/151610959/15ce95ce-c0b6-4b00-9158-fe4af289dbf8)

**Comment by Iamlovingit** [comment]
试一下这个启动命令，把盘符改为大写

```
docker run -d --name all-in-one -p 5050:5050 -v D:\yuandemo\Yuan2-2B-hf:/models yuanmodel/yuanchat:all-cpu
```

**Comment by Legionee** [comment]
还是空的

**Comment by Iamlovingit** [comment]
加这个qq群里交流吧
![image](https://github.com/IEIT-Yuan/YuanChat/assets/38182824/0284d2e3-e44b-48f4-a065-0052494b97e2)

**Comment by Iamlovingit** [comment]
教程中修改代码有误
https://github.com/IEIT-Yuan/YuanChat/blob/75413f53d6e3e8c8f0835daea17385cdbe4c818a/docs/%E5%9C%A8%E7%AC%94%E8%AE%B0%E6%9C%AC%E4%B8%8A%E5%BF%AB%E9%80%9F%E9%83%A8%E7%BD%B2YuanModel%E5%92%8CYuanChat.md?plain=1#L28

**Comment by Iamlovingit** [comment]
#8 fix bug
